### ISSUE TITLE
[1.0.0] Socket permissions will reset during startup

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/ospd-openvas#124]
When the log message "DEBUG: (ospd_openvas.daemon) Loading vts in memory." comes, the socket permission are as request by  --socket-mode. But after the message "DEBUG: (ospd_openvas.daemon) Finish loading up vts." the socket permission are reset to 0755.

**Comment by jjnicola** [comment]
It was already fixed with PR greenbone/ospd#158
