### ISSUE TITLE
unable to change socket_mode

### ISSUE THREAD

**Issue by blshkv** [greenbone/ospd-openvas#170]
I have tried to specify in both config file ```/etc/openvas/ospd.conf``` and command line via --socket-mode=0o777 but none worked.

Would you have any ideas?

I'm using the latest version 1.0.0

**Comment by blshkv** [comment]
I found the code in the following file:
https://github.com/greenbone/ospd/blob/master/ospd/server.py#L218-L219

It looks like ```chmod``` is called before the socket is getting created.

**Comment by blshkv** [comment]
https://github.com/greenbone/ospd/commit/bf5306798cc7b22eaddefa13d4e76cd3599a54b0

**Comment by jjnicola** [comment]
Hi @blshkv,
it was already fixed with PR greenbone/ospd#157. The next release will include the patch.
Regards
