### ISSUE TITLE
Start ospd-openvas - socket + port

### ISSUE THREAD

**Issue by dgiorgio** [greenbone/ospd-openvas#174]
```
/usr/local/bin/ospd-openvas --pid-file /var/run/ospd/ospd.pid --unix-socket /var/run/ospd/ospd.sock -m 0777 --key-file /usr/local/var/lib/gvm/private/CA/serverkey.pem --cert-file /usr/local/var/lib/gvm/CA/servercert.pem --ca-file /usr/local/var/lib/gvm/CA/cacert.pem -L DEBUG -f
```
When not specified "-b 0.0.0.0 -p 51234", the .sock file is created.

```
/usr/local/bin/ospd-openvas --pid-file /var/run/ospd/ospd.pid --unix-socket /var/run/ospd/ospd.sock -m 0777 -b 0.0.0.0 -p 51234 --key-file /usr/local/var/lib/gvm/private/CA/serverkey.pem --cert-file /usr/local/var/lib/gvm/CA/servercert.pem --ca-file /usr/local/var/lib/gvm/CA/cacert.pem -L DEBUG -f
```
When "-b 0.0.0.0 -p 51234" is specified, the .sock file is not created.

Is it possible to start the service by listening on the port, and the socket?

**Comment by dgiorgio** [comment]
Issue opened in the wrong place?

**Comment by bjoernricks** [comment]
This is a support question not a bug report. Therefore it fits best to https://community.greenbone.net. But nevertheless to answer your question. No it is not possible to listen on both a tcp socket and a unix domain socket at the same time.
