### ISSUE TITLE
TypeError: lrem() got an unexpected keyword argument 'count'

### ISSUE THREAD

**Issue by pomac303** [greenbone/ospd-openvas#179]
With ospd-openvas 1.0.0

2020-01-14 13:05:29,249 OSPD - openvas: ERROR: (ospd.ospd) While scanning aa,bb,cc,dd/xx:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ospd/ospd.py", line 777, in parallel_scan
    ret = self.exec_scan(scan_id, target)
  File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 1441, in exec_scan
    self.openvas_db.remove_list_item('internal/dbindex', i)
  File "/usr/lib/python3/dist-packages/ospd_openvas/db.py", line 291, in remove_list_item
    ctx.lrem(key, count=LIST_ALL, value=value)

**Comment by jjnicola** [comment]
Hi @pomac303,
please check you are using the right python-redis version. lrem() signature changed and the required version is redis>=3.0.1.
Closing here because it is not a bug.
Regards.

**Comment by pomac303** [comment]
Ok, not available for LTS ubuntu - vill try to arrange it.

**Comment by jjnicola** [comment]
Hi @pomac303,
did you get working the right python-redis version in your environment? I wonder if this caused the other two issues you opened. It is just keep the issue tracker cleaner as possible. Let me know, then I can close the other issues.
Regards

**Comment by pomac303** [comment]
Not yet, and i hit the two other errors first...

**Comment by pomac303** [comment]
apt show python3-redis
Package: python3-redis
Version: 3.3.11-2
---

Right now, will comment in the other bug report as well... Stuck at 3% even if all nmap processes are done
