### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by pomac303** [greenbone/ospd-openvas#181]
With ospd-openvas 1.0.0 - might be related to the timeout change - worked around this by calling continue if None == _custom

jan 14 12:59:55 openvas ospd-openvas[25014]: Traceback (most recent call last):
jan 14 12:59:55 openvas ospd-openvas[25014]:   File "/usr/bin/ospd-openvas", line 11, in <module>
jan 14 12:59:55 openvas ospd-openvas[25014]:     load_entry_point('ospd-openvas==1.0.0', 'console_scripts', 'ospd-openvas')()
jan 14 12:59:55 openvas ospd-openvas[25014]:   File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 1454, in main
jan 14 12:59:55 openvas ospd-openvas[25014]:     daemon_main('OSPD - openvas', OSPDopenvas)
jan 14 12:59:55 openvas ospd-openvas[25014]:   File "/usr/lib/python3/dist-packages/ospd/main.py", line 159, in main
jan 14 12:59:55 openvas ospd-openvas[25014]:     daemon.init()
jan 14 12:59:55 openvas ospd-openvas[25014]:   File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 293, in init
jan 14 12:59:55 openvas ospd-openvas[25014]:     self.load_vts()
jan 14 12:59:55 openvas ospd-openvas[25014]:   File "/usr/lib/python3/dist-packages/ospd_openvas/daemon.py", line 413, in load_vts
jan 14 12:59:55 openvas ospd-openvas[25014]:     _name = _custom.pop('name')
jan 14 12:59:55 openvas ospd-openvas[25014]: AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by jjnicola** [comment]
Ospd-openvas has changed a lot since v20.08 in the way it handles the VTs. Currently it doesn't use the interal VT storage and communicates directly with redis. This issue is not present anymore in the current stable version. For references about this changes see PR #236.
Therefore I close the issue here.
