### ISSUE TITLE
KeyError: 'vt_groups' on command 'start_scan'

### ISSUE THREAD

**Issue by MrSuicideParrot** [greenbone/ospd-openvas#218]
I'm trying to create an independent scanner with openvas 7.0, ospd-openvas and gvm-cli to control it.

This error happened in a Debian 10, with everything installed from the latest stable release. More precisely, in the case of ospd-openvas, I installed it from pip.
```
$ ospd-openvas --version
OSP Server for openvas: 1.0.0
OSP: 1.2
OSPd: 2.0.0
```

When I try the examples of [OSP API](https://docs.greenbone.net/API/OSP/osp.html) and send the "start_scan" command, the server responds with status code 200, but in the backend the scan fails with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ospd/ospd.py", line 777, in parallel_scan
    ret = self.exec_scan(scan_id, target)
  File "/usr/local/lib/python3.7/dist-packages/ospd_openvas/daemon.py", line 1351, in exec_scan
    nvts_list, nvts_params = self.process_vts(nvts)
  File "/usr/local/lib/python3.7/dist-packages/ospd_openvas/daemon.py", line 1087, in process_vts
    vtgroups = vts.pop('vt_groups')
KeyError: 'vt_groups'
```
start_scan command:
```xml
<start_scan target="192.168.1.20" ports="80, 443"><scanner_params><target_port>443</target_port><use_https>1</use_https><profile>fast_scan</profile></scanner_params></start_scan>
```
In the scan report appears an error, `Host process failure ('vt_groups')`. 

Any ideas about this error? I was unable to discover the reason for this error.

**Comment by jjnicola** [comment]
Hi @MrSuicideParrot,
Did you tried adding some VT ? You will need to especified the VTs you want to launch or a some VT family (group of vt).
Your start_scan command should have a <vt_selection> subelement

**Comment by MrSuicideParrot** [comment]
Thanks a lot! I didn't specified any VT...

**Comment by bjoernricks** [comment]
@jjnicola we should return an error if the vt_selection is missing from the response
