### ISSUE TITLE
feed-update.lock issues

### ISSUE THREAD

**Issue by BasvanH** [greenbone/ospd-openvas#267]
### GVM versions
**gsa:** 9.0.0 git-87b20cb24-gsa-9.0
**gvm:** 9.0.1 git-7518695a-gvmd-9.0

### Environment
Ubuntu 18.04 TLS
Greenbone build from git

We notice that after some days the auto download of NVT's does no longer work properly. When running `greenbone-nvt-sync` under the `gvm` user gives no return, it exits immediately. I think it's because the `feed-update.lock` lock file is present in the run directory which should not be there.

When I remove 'feed-update.lock', I can successfully run `greenbone-nvt-sync`.

Also, when I reboot the server, the gvmd complains that the `ospd.sock` isn't present. This is true, because `ospd-openvas` process seems to be locked when starting. Again, when I manually remove 'feed-update.lock', the ospd scanner continue's its start and after it's loaded the `gvmd` can read its socket.

If I leave the 'feed-update.lock' in place, it never ever gets deleted. There seems to be an issue with the 'feed-update.lock` not being correctly handled/deleted. I have this in three separate setups with the exact same behavior.

**Comment by cfi-gb** [comment]
There are various unreleased updates to the locking topic which might already solve this:

https://github.com/greenbone/ospd-openvas/pull/257
https://github.com/greenbone/openvas/pull/507
https://github.com/greenbone/gvmd/pull/1089
https://github.com/greenbone/gvmd/pull/1088

**Comment by jjnicola** [comment]
Fixed with greenbone/openvas#527
