### ISSUE TITLE
Resumed tasks may generate invalid target value error on ospd-openvas side

### ISSUE THREAD

**Issue by wisukind** [greenbone/ospd-openvas#284]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```
**Expected behaviour:**
Tasks resumed shouldn't produce any target errors on ospd-openvas side.

**Actual behaviour:**
If a task stop while running for whatever reason; resuming it may generated continuous Invalid target value errors on ospd-openvas side. Target has not been changed, and starting the task again (without resuming it) will not produce those errors:
```

2020-07-10 11:58:10,604 OSPD - openvas: INFO: (ospd.network) : Invalid target value
2020-07-10 11:58:10,772 OSPD - openvas: INFO: (ospd.network) : Invalid target value
2020-07-10 11:58:11,618 OSPD - openvas: INFO: (ospd.network) : Invalid target value
2020-07-10 11:58:11,779 OSPD - openvas: INFO: (ospd.network) : Invalid target value
2020-07-10 11:58:12,628 OSPD - openvas: INFO: (ospd.network) : Invalid target value
....
```
It is not clear if this bug has any effect on scans results, since openvas logs doesn't show any errors and resume the scans without problem; while no error is reported on gsad / gvmd side.

**How To reproduce:**
- Start a task
- After at least 50-60% achieved; stop the task.
- Once stopped; resume the task.
- Look at ospd-openvas logs for the upon errors.

**Note:** The issue do not always occurs; but is likely to occurs on big tasks (/22 or higher)

**Comment by jjnicola** [comment]
Hi @wisukind,
do still have this issue? Are you already using the version 20.08? if you aren't experimenting this issue in a 20.08 version, please feel free to close this issue, as the fix is not likely to be backported

**Comment by bjoernricks** [comment]
Please re-open if the issue still consists with the current 20.08 version.
