### ISSUE TITLE
Feature Request: Align logging timezone with gvmd, gsad and openvas (UTC)

### ISSUE THREAD

**Issue by wisukind** [greenbone/ospd-openvas#288]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```

**Expected behaviour:**
Use same timezone for logging than gvmd, gsad and openvas.

**Current behaviour:**
Currently ospd-openvas use a specific time zone for events logging. This would be perfect if gsad, gvmd and openvas would use it as well. Unfortunately, gsad, gvmd and openvas uses UTC for events logging; so it becomes difficult to track issues between gvmd, openvas and ospd-openvas because timezones are not the same, especially since none of those time zones are the local time zone. 

It would be nice if all tools could use the same time zone, and preferably the local time zone of the machine.

This feature request is complimentary of #287

**Comment by Kraemii** [comment]
I just fixed it and changed the timezone of the Logger to UTC. See: https://github.com/greenbone/ospd/pull/394
