### ISSUE TITLE
Pulling the active scans with gvm-cli

### ISSUE THREAD

**Issue by frankerooney** [greenbone/ospd-openvas#358]
Environment:
Greenbone Vulnerability Manager 20.08.0git-c04cad16-gvmd-20.08
Greenbone Security Assistant 20.08.0git-d26e061f9-gsa-20.08
OSP Server for openvas: 20.8.0
OSP: 20.8.1
OSPd OpenVAS: 20.8.1
gvm-cli 20.10.2.dev1 (API version 20.11.3)
Ubuntu 20.04

I have an issue where gvmd believes that running scans are terminating, often "interrupted", and I've yet to figure out quite why.
In the meantime, I am also using the "max scans" setting in ospd-openvas to type and keep things trimmed down to 2 parallel scans, and also often find that although gvmd says the scans are not running, ospd thinks they are; scans queue and I often get "(ospd.ospd) Not possible to run a new scan. Max scan limit set to 2 reached." in the logs. I realise I could just remove this limit, but I'd like to have things a bit more exact:

I was trying to make it all a bit more "closed-loop" by using gvm-cli to pull a list of known running scans using

 gvm-cli --protocol OSP socket --socketpath /opt/gvm/var/run/ospd.sock --xml="<get_scans/>"

but unlike the gmp protocol, this does not produce a list, just an error ; "Response Error 400. No scan_id attribute". 
Is there a way of simply pulling the number of running scans on the ospd side without knowing the "scan_id", so I can equate them to the number of running scans within gvm and restart the service if different? Even more ideally I'd also know the uuids or some other attribute which could be used to match task to scan so I can selectively cull stuff in the scanner.
I realise the uuids are dissimilar so I can't query a specific scan without scouring logs to see what's running and get the uuids, more difficult and hacky to script whilst rotating logs and so on behind the scenes.

It's my first delve into the use of gvm-cli with the OSP protocol so I may have missed something!

Kind Regards
Andy

**Comment by jjnicola** [comment]
Discussed in https://community.greenbone.net/t/get-scans-scan-id-wildcard-possible/7742
Scan ID is mandatory for get_scans https://github.com/greenbone/ospd/pull/270

**Comment by frankerooney** [comment]
@jjnicola , thank you for the update. Before close, may i ask what the reason was the iteration behaviour was removed; there isn't anything in the description of the commit that explains it?
 It seems there is no way to compare gvmd and ospd scans directly, as they do not share uuids, and ospd seems to not always cull scans when gvmd no longer considers them running, so i need to have a think about a different way of ensuring this, maybe regularly restarting the ospd service when gvmd is idle.
Thank you

**Comment by jjnicola** [comment]
Hi @frankerooney,
gvmd and ospd shared the UUID. The UUID is the report id shown in GSA.
E.g click the scan progress bar for a running scan, the report page for the scan is opened and you can see the UUID on the top right, close to the filters. Also, you can see the search for the IDs in the log.
Also, there is an ospd-openvas option that you can set in the config file to delete automatically the [forgotten scans](https://github.com/greenbone/ospd-openvas/blob/master/docs/ospd-openvas.8#L101). This option is disabled per default, and of course, you all info related to stopped scans. Maybe this is useful for you.

**Comment by frankerooney** [comment]
Great, all very useful, thank you. Still learning the ropes so forgive the lack of knowledge on my part.
Kind regards
