### ISSUE TITLE
python 3.9 support, importlib.metadata.PackageNotFoundError: ospd-openvas 

### ISSUE THREAD

**Issue by atomicturtle** [greenbone/ospd-openvas#407]
Environment: Fedora 33

python3-3.9.0-1.fc33.x86_64

```
export PYTHONPATH=/opt/atomicorp/lib/python3.9/site-packages 

[gvm@fc33 ~]$ /opt/atomicorp/bin/ospd-openvas --help
Traceback (most recent call last):
  File "/opt/atomicorp/bin/ospd-openvas", line 33, in <module>
    sys.exit(load_entry_point('ospd-openvas==21.4.0', 'console_scripts', 'ospd-openvas')())
  File "/opt/atomicorp/bin/ospd-openvas", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib64/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib64/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ospd-openvas

```

I believe the format for python 3.9 handling metadata has changed. So my guess is that python setup isnt installing things  if you declare PYTHONPATH 3.9: 

export PYTHONPATH=/opt/atomicorp/lib/python3.9/site-packages
python3 setup.py install --prefix=/opt/atomicorp/

This does however work just fine if you are not declaring the PYTHONPATH, and write (or overwrite in this case) to the system site-packages at /usr/lib/python3.9/site-packages.

**Comment by bjoernricks** [comment]
I don't think there is anything we can do about this. We use the standard Python toolchain (setuptools) and I can't find any suspicious in the setup.py file besides not declaring Python 3.9 support. Maybe you can try adding that to the file and check again?

**Comment by atomicturtle** [comment]
Still working this one, python isn't my wheelhouse but if I can solve it I'll send a PR. Otherwise redirect everyone here on this so we can build some community momentum around it.  I did try adding 3.9 in here, but it didnt help. I feel like the behavior for metadata in 3.9 has changed, so I'll keep digging

**Comment by atomicturtle** [comment]
Some followup, not a real solution yet but it looks like this is happening because easy-install.pth doesnt get created when you specify a prefix to setup.py. Probably because it (easy-install) is being/is deprecated in 3.9. For what its worth if you're installing to  /usr or /usr/local, it does create the easy-install.pth file, so maybe this is something conditional in the way 3.9 setuptools works.

**Comment by ArnoStiefvater** [comment]
We are using python 3.9 now. It should work now.
If this is not the case please reopen the issue.
