### ISSUE TITLE
v20.4.1 sudoers problem

### ISSUE THREAD

**Issue by BasvanH** [greenbone/ospd-openvas#446]
Hi,

Just upgraded to tag version v20.4.1 . When running a task I get permissions problems. I've got my sudoers in place, just like with V20.4.0 .

```
libgvm boreas:WARNING:2021-06-25 18h59.19 utc:3263: set_socket: failed to open ICMPV4 socket: Operation not permitted
libgvm boreas:WARNING:2021-06-25 18h59.19 utc:3263: start_alive_detection. Boreas could not initialise alive detection. Boreas was not able to open a new socket. Exit Boreas.
```

**visudo**
`Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/gvm/sbin"`

**/etc/sudoers.d/gvm**
gvm ALL = NOPASSWD: /opt/gvm/sbin/openvas
gvm ALL = NOPASSWD: /opt/gvm/sbin/gsad

Root dir is '/opt/gvm/'.

Has anything changed with v20.4.1? Dont understand whats the case here...

Regards,
Bastiaan

**Comment by BasvanH** [comment]
'<servername> : Jun 25 21:44:27 : gvm : a password is required ; TTY=unknown ; PWD=/opt/gvm ; USER=root ; COMMAND=**/usr/local/sbin/openvas** -s'

Somehow some binaries got placed in the wrong directories. I will rebuild from scatch.

**Comment by cfi-gb** [comment]
For anyone stumbling over e.g. a search engine on this issue, a user in the community reported that the missing permissions could be caused by AppArmor on Ubuntu:

> Learned that there is something in Ubuntu that is stopping it from running. AppArmor. My solution was to start over and I have loaded Debian and this issue was resolved.
>
> https://forum.greenbone.net/t/boreas-could-not-initialise-alive-detection/14655/9

**Comment by cfi-gb** [comment]
@greenbone/ospd-maintainers This probably should be also moved to the https://github.com/greenbone/gvm-libs repository as `ospd-openvas` seems to be unrelated.
