### ISSUE TITLE
openvas.service error on systemctl start openvas

### ISSUE THREAD

**Issue by Afromanfro** [greenbone/ospd-openvas#563]
Hi.
When running systemctl start openvas i got this error. I've tried different branch and tags and now i'm on 20.8.2 branch oldstable for ospd-openvas and also for ospd.

`openvas.service - Control the OpenVAS service
     Loaded: loaded (/etc/systemd/system/openvas.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2021-12-13 13:04:05 UTC; 35s ago
    Process: 7261 ExecStartPre=/usr/bin/rm -rf /opt/gvm/var/run/ospd-openvas.pid /opt/gvm/var/run/ospd.sock /opt/gvm/var/run/gvmd.sock (code=exited, status=0/SUCCESS)
    Process: 7262 ExecStart=/usr/bin/python3 /opt/gvm/bin/ospd-openvas --pid-file /opt/gvm/var/run/ospd-openvas.pid --log-file /opt/gvm/var/log/gvm/ospd-openvas.log --lock-file-dir /opt/gv>
   Main PID: 7262 (code=exited, status=1/FAILURE)

Dec 13 13:04:05 openvas python3[7262]:     return self.execute_command("KEYS", pattern, **kwargs)
Dec 13 13:04:05 openvas python3[7262]:   File "/opt/gvm/lib/python3.8/site-packages/redis-4.1.0rc2-py3.8.egg/redis/client.py", line 1156, in execute_command
Dec 13 13:04:05 openvas python3[7262]:     conn = self.connection or pool.get_connection(command_name, **options)
Dec 13 13:04:05 openvas python3[7262]:   File "/opt/gvm/lib/python3.8/site-packages/redis-4.1.0rc2-py3.8.egg/redis/connection.py", line 1240, in get_connection
Dec 13 13:04:05 openvas python3[7262]:     connection = self.make_connection()
Dec 13 13:04:05 openvas python3[7262]:   File "/opt/gvm/lib/python3.8/site-packages/redis-4.1.0rc2-py3.8.egg/redis/connection.py", line 1280, in make_connection
Dec 13 13:04:05 openvas python3[7262]:     return self.connection_class(**self.connection_kwargs)
Dec 13 13:04:05 openvas python3[7262]: TypeError: __init__() got an unexpected keyword argument 'redis_connect_func'
Dec 13 13:04:05 openvas systemd[1]: openvas.service: Main process exited, code=exited, status=1/FAILURE
Dec 13 13:04:05 openvas systemd[1]: openvas.service: Failed with result 'exit-code'.`

**Comment by y0urself** [comment]
The 20.8 (oldstable) version of our software is EOL. If this error also occurs on stable please create another Issue! Thanks.
