### ISSUE TITLE
Current docker image cannot start because of redis-py bug

### ISSUE THREAD

**Issue by korzorro** [greenbone/ospd-openvas#857]
### Expected behavior
The docker container for this project should build and connect to the redis server container without error.

### Actual behavior
The current docker container build (as of Feb 8 ~09:00 UTC) fails to start and returns the following error:
```
AttributeError: 'UnixDomainSocketConnection' object has no attribute '_command_packer'
```

### Steps to reproduce
Follow [these instructions](https://greenbone.github.io/docs/latest/22.4/container/index.html). Notice that the container doesn't start properly.

### Proposed solution
[Redis 4.5.1](https://github.com/redis/redis-py/releases) fixed this bug. Rebuild this container and push it, ensuring that redis-py v4.5.1 is installed.

**Comment by bjoernricks** [comment]
I've rebuild and uploaded the images for amd64 and arm64.
