### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by Blck4** [greenbone/ospd-openvas#877]
gvm-cli --protocol OSP socket --sockpath /var/run/ospd/ospd.sock --xml "<start_scan><scan_id>111111</scan_id><targets><target>www.xx.com</target></targets><ports>U:80</ports><credentials>11</credentials></start_scan>"

OSPD[2155] 2023-03-18 02:08:33,877: ERROR: (ospd.ospd) While handling client command:
Traceback (most recent call last):
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/ospd.py", line 558, in handle_client_stream
    self.handle_command(data, stream)
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/ospd.py", line 1077, in handle_command
    response = command.handle_xml(tree)
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/command/command.py", line 617, in handle_xml
    scan_id = self._daemon.create_scan(
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/ospd.py", line 1255, in create_scan
    return self.scan_collection.create_scan(
  File "/opt/atomicorp/lib/python3.8/site-packages/ospd/scan.py", line 321, in create_scan
    credentials = target.pop('credentials')
AttributeError: 'NoneType' object has no attribute 'pop'

version:
OpenVAS 22.4.1
gvm-libs 22.4.1
Most new code since 2005: (C) 2022 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

why?

**Comment by jjnicola** [comment]
Hello @Blck4, 
You are using a the start_scan command with an incomplete XML cmd. It is missing the target element, and others like the scanner_params and vt_selection elements.
Take a look into the [OSP documentation](https://docs.greenbone.net/API/OSP/osp-22.04.html#command_start_scan), you will find some examples there.

As example, this runs an authenticated scan against a target to check ssh authentication (the single VT) using the given credentials and port.

```
<start_scan parallel="1" scan_id="552cd046-99fd-494a-bb39-100bf36d2ee4">
  <targets>
    <target>
      <hosts>192.168.1.1</hosts>
      <exclude_hosts/>
      <ports>T:22</ports>
      <credentials>
        <credential type="up" service="ssh" port="22">
          <username>user</username>
          <password>pass</password>
        </credential>
      </credentials>
    </target>
  </targets>
  <scanner_params/>
  <vt_selection>
    <vt_single id="1.3.6.1.4.1.25623.1.0.90022"/>
  </vt_selection>
</start_scan>
```

Regards!

**Comment by jjnicola** [comment]
BTW, I tested something like you, and I don't get backtrace
```
gvm-cli --protocol OSP socket --socketpath ~/install/var/run/ospd/openvas.sock -X "<start_scan><scan_id>111111</scan_id>192.168.0.1U:8080</start_scan>" --pretty
Response Error 400. No targets or ports
```
Are you using the right ospd-version?

try this:
`$ gvm-cli --protocol OSP socket --socketpath ~/install/var/run/ospd/openvas.sock -X "<get_version/>" --pretty`

**Comment by jjnicola** [comment]
I closed the issue because it is not a bug. If you have more question, please use the [Greenbone Forum](https://forum.greenbone.net/)
