### ISSUE TITLE
paho-mqtt pypi package breaking changes

### ISSUE THREAD

**Issue by martinboller** [greenbone/ospd-openvas#968]
### Expected behavior
ospd-openvas should connect to MQTT creating MQTTClient  using paho-mqtt.
Note version 1.6.1 still works, this only fails when upgrading to paho-mqtt 2.0.0 

### Actual behavior
with paho-mqtt version 2.0.0, producing the following error for both ospd-openvas and notus-scanner

Traceback (most recent call last):
File “/opt/gvm/gvmpy/lib/python3.11/site-packages/paho/mqtt/client.py”, line 874, in del
self._reset_sockets()
File “/opt/gvm/gvmpy/lib/python3.11/site-packages/paho/mqtt/client.py”, line 1133, in _reset_sockets
self._sock_close()
File “/opt/gvm/gvmpy/lib/python3.11/site-packages/paho/mqtt/client.py”, line 1119, in _sock_close
if not self._sock:
^^^^^^^^^^
AttributeError: ‘MQTTClient’ object has no attribute ‘_sock’

### Steps to reproduce
install paho-mqtt version 2.0.0

Error with several different versions of ospd-openvas (tested latest and 2 previous releases)

**Comment by jjnicola** [comment]
https://github.com/eclipse/paho.mqtt.python/issues/814

**Comment by jjnicola** [comment]
Hi @martinboller ,
Thanks for reporting this. Notus-scanner and ospd-openvas should be fixed.
